### ISSUE TITLE
Android module next implementations

### ISSUE THREAD

**Issue by michelelazzarato** [hansemannn/titanium-bluetooth#32]
Hi, I try to use ti.bluetooth module on android device but unfortunately few method are present and it is unusable.
When this module for Android platform will be upgraded like iOS platform?
In alternative how can i connect BLE device with android device?
Thanks in advance,

    Michele.

**Comment by hansemannn** [comment]
Hi! There are no plans to update Android as well. Feel free to submit new changes, thats why I have made it open source.

**Comment by PietroGranati** [comment]
Any news?

**Comment by michelelazzarato** [comment]
Hi Pietro no any news.
Where are you from?


Inviato da iPhone

**Comment by m1ga** [comment]
@michelelazzarato why should it be part of the SDK just because it is part of the phone? That's the beauty of modules, that you just can add them if you need it or not and that it can be updated outside of the SDK.

I don't have any use-case for BT/BLE at the moment, so won't update the Android part to be feature complete. But you could have a look at the Hyperloop example: https://github.com/m1ga/hyperloop.bluetooth
and extend the missing modules yourself. It's using LMBluetoothSdk that has many methods that should be straight forward to implement in hyperloop.

**Comment by michelelazzarato** [comment]
Hi everyone,
 i have solved.
Thanks a lot,

   Michele.
